### ISSUE TITLE
Change field type from 'text' to other type

### ISSUE THREAD

**Issue by bumpmann** [webshell/materia-server#14]
### Expected behavior

When updating a field type from text to integer (or boolean, date...), this should cast the data to the new type (c.f. http://stackoverflow.com/questions/13170570/change-type-of-varchar-field-to-integer-cannot-be-cast-automatically-to-type-i)
### Actual behavior

The SQL request looks like `ALTER TABLE "..." ALTER COLUMN "..." TYPE TEXT`
### Step to reproduce the behavior

Changing a field type from type text to number, date or boolean throws an error when it should cast the data to the new type:

`column "..." cannot be cast automatically to type ...`

---
- Materia Version: pre-release

**Comment by arhka-win** [comment]
@bumpmann still have this bug with Postgres. Works only with this 'INTEGER USING CAST("column" as INTEGER)', what is not the same as written in documentation. Could you tell me, when this bug is going to be fixed, please?
