### ISSUE TITLE
command materia start don't work after a global installation

### ISSUE THREAD

**Issue by GeoAstronaute** [webshell/materia-server#20]
### Expected behavior
launch the server with the command line `materia start`

### Actual behavior
Error in the console when running `materia start`: 
```
command not found
/usr/local/bin/materia: line 3: syntax error near unexpected token `('
/usr/local/bin/materia: line 3: `let argv = require('minimist')(process.argv.slice(2))'
```
Actually the server can be run with `forever start ./node_modules/materia-server/cli/index.js start`

### Step to reproduce the behavior

* `sudo npm install -g materia-server`

* `materia start`

---

* Materia Version: v0.1.1

**Comment by thyb** [comment]
The commit https://github.com/webshell/materia-server/commit/718e4ab56abf8e8b8bc674b367c413527eb2e936 should fix this issue. It has been released in v0.1.2.

Thanks for the feedback ! :)
